server:
  port: 9600

logging:
  level:
    com.pw.wispne.iniesta: debug

  path: logs
spring:
  messages:
    basename: i18n.login

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://129.28.193.232:3306/mccloud?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver