server:
  port: 9600

logging:
  level:
    com.pw.wispne.iniesta: debug

  path: logs
spring:
  messages:
    basename: i18n.login

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss